<Project Sdk="Microsoft.NET.Sdk">



  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>EcomMicroService.Cms</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EcomMicroService.Cms.Application\EcomMicroService.Cms.Application.csproj" />
    <ProjectReference Include="..\EcomMicroService.Cms.Domain.Tests\EcomMicroService.Cms.Domain.Tests.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
  </ItemGroup>

</Project>
