<Project Sdk="Microsoft.NET.Sdk.Web">

  

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>EcomMicroService.Administration</RootNamespace>
        <PreserveCompilationReferences>true</PreserveCompilationReferences>
        <UserSecretsId>EcomMicroService.Administration-c2d31439-b723-48e2-b061-5ebd7aeb6010</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <DockerfileContext>..\..\..\..</DockerfileContext>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\shared\EcomMicroService.Microservice.Shared\EcomMicroService.Microservice.Shared.csproj" />
        <ProjectReference Include="..\..\..\..\shared\EcomMicroService.ServiceDefaults\EcomMicroService.ServiceDefaults.csproj" />
        <ProjectReference Include="..\..\..\identity\src\EcomMicroService.IdentityService.Application.Contracts\EcomMicroService.IdentityService.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\..\identity\src\EcomMicroService.IdentityService.EntityFrameworkCore\EcomMicroService.IdentityService.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\..\..\saas\src\EcomMicroService.SaaS.Application.Contracts\EcomMicroService.SaaS.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\..\saas\src\EcomMicroService.SaaS.EntityFrameworkCore\EcomMicroService.SaaS.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\..\..\catalog\src\EcomMicroService.Catalog.Application.Contracts\EcomMicroService.Catalog.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\..\ordering\src\EcomMicroService.Ordering.Application.Contracts\EcomMicroService.Ordering.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\..\basket\src\EcomMicroService.Basket.Application.Contracts\EcomMicroService.Basket.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\..\customer\src\EcomMicroService.Customer.Application.Contracts\EcomMicroService.Customer.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\..\payment\src\EcomMicroService.Payment.Application.Contracts\EcomMicroService.Payment.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\..\marketing\src\EcomMicroService.Marketing.Application.Contracts\EcomMicroService.Marketing.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\..\cms\src\EcomMicroService.Cms.Application.Contracts\EcomMicroService.Cms.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\..\notification\src\EcomMicroService.Notification.Application.Contracts\EcomMicroService.Notification.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\..\projects\src\EcomMicroService.Projects.Application.Contracts\EcomMicroService.Projects.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\src\EcomMicroService.Administration.HttpApi\EcomMicroService.Administration.HttpApi.csproj" />
        <ProjectReference Include="..\..\src\EcomMicroService.Administration.Application\EcomMicroService.Administration.Application.csproj" />
        <ProjectReference Include="..\..\src\EcomMicroService.Administration.EntityFrameworkCore\EcomMicroService.Administration.EntityFrameworkCore.csproj" />
    </ItemGroup><ItemGroup>
      <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    </ItemGroup>

</Project>
