<Project Sdk="Microsoft.NET.Sdk">



  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>EcomMicroService.Customer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <ProjectReference Include="..\EcomMicroService.Customer.EntityFrameworkCore.Tests\EcomMicroService.Customer.EntityFrameworkCore.Tests.csproj" />
  </ItemGroup>

</Project>
