<Project Sdk="Microsoft.NET.Sdk">



  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>EcomMicroService.Basket</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EcomMicroService.Basket.Application\EcomMicroService.Basket.Application.csproj" />
    <ProjectReference Include="..\EcomMicroService.Basket.Domain.Tests\EcomMicroService.Basket.Domain.Tests.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
  </ItemGroup>

</Project>
