<Project Sdk="Microsoft.NET.Sdk">

  

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>EcomMicroService.Ordering</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Volo.Abp.Http.Client" Version="$(AbpVersion)" />
        <ProjectReference Include="..\EcomMicroService.Ordering.Application.Contracts\EcomMicroService.Ordering.Application.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="**\*generate-proxy.json" />
        <Content Remove="**\*generate-proxy.json" />
    </ItemGroup>

</Project>
