<Project Sdk="Microsoft.NET.Sdk">



  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>EcomMicroService.Catalog</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="$(MicrosoftAspNetVersion)" />
    <ProjectReference Include="..\..\src\EcomMicroService.Catalog.EntityFrameworkCore\EcomMicroService.Catalog.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\EcomMicroService.Catalog.TestBase\EcomMicroService.Catalog.TestBase.csproj" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.Sqlite" Version="$(AbpVersion)" />
  </ItemGroup>

</Project>
