<Project Sdk="Microsoft.NET.Sdk">

  

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>EcomMicroService.Catalog</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="Volo.Abp.Mapperly" Version="$(AbpVersion)" />
        <PackageReference Include="Volo.Abp.Ddd.Application" Version="$(AbpVersion)" />
        <ProjectReference Include="..\EcomMicroService.Catalog.Application.Contracts\EcomMicroService.Catalog.Application.Contracts.csproj" />
        <ProjectReference Include="..\EcomMicroService.Catalog.Domain\EcomMicroService.Catalog.Domain.csproj" />
    </ItemGroup>

</Project>
