<Project Sdk="Microsoft.NET.Sdk">

  

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>EcomMicroService.IdentityService</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="OpenIddict.Abstractions" Version="$(OpenIddictAbstractionsVersion)" />
        <PackageReference Include="Volo.Abp.Account.Application.Contracts" Version="$(AbpVersion)" />
        <PackageReference Include="Volo.Abp.Ddd.Application.Contracts" Version="$(AbpVersion)" />
        <PackageReference Include="Volo.Abp.Authorization" Version="$(AbpVersion)" />
        <PackageReference Include="Volo.Abp.Identity.Application.Contracts" Version="$(AbpVersion)" />
        <ProjectReference Include="..\EcomMicroService.IdentityService.Domain.Shared\EcomMicroService.IdentityService.Domain.Shared.csproj" />
    </ItemGroup></Project>
