<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <DockerfileContext>..\..</DockerfileContext>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="IdentityModel" Version="7.0.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="$(MicrosoftAspNetVersion)" />
        <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
        <PackageReference Include="OpenIddict.Abstractions" Version="$(OpenIddictAbstractionsVersion)" />
        <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.0" />
        <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
        <PackageReference Include="Volo.Abp.Autofac" Version="$(AbpVersion)" />
        <PackageReference Include="Volo.Abp.BackgroundJobs.Abstractions" Version="$(AbpVersion)" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\services\administration\src\EcomMicroService.Administration.Application.Contracts\EcomMicroService.Administration.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\services\administration\src\EcomMicroService.Administration.EntityFrameworkCore\EcomMicroService.Administration.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\..\services\identity\src\EcomMicroService.IdentityService.Application.Contracts\EcomMicroService.IdentityService.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\services\identity\src\EcomMicroService.IdentityService.EntityFrameworkCore\EcomMicroService.IdentityService.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\..\services\catalog\src\EcomMicroService.Catalog.Application.Contracts\EcomMicroService.Catalog.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\services\catalog\src\EcomMicroService.Catalog.EntityFrameworkCore\EcomMicroService.Catalog.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\..\services\basket\src\EcomMicroService.Basket.Application.Contracts\EcomMicroService.Basket.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\services\basket\src\EcomMicroService.Basket.EntityFrameworkCore\EcomMicroService.Basket.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\..\services\ordering\src\EcomMicroService.Ordering.Application.Contracts\EcomMicroService.Ordering.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\services\ordering\src\EcomMicroService.Ordering.EntityFrameworkCore\EcomMicroService.Ordering.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\..\services\customer\src\EcomMicroService.Customer.Application.Contracts\EcomMicroService.Customer.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\services\customer\src\EcomMicroService.Customer.EntityFrameworkCore\EcomMicroService.Customer.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\..\services\payment\src\EcomMicroService.Payment.Application.Contracts\EcomMicroService.Payment.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\services\payment\src\EcomMicroService.Payment.EntityFrameworkCore\EcomMicroService.Payment.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\..\services\marketing\src\EcomMicroService.Marketing.Application.Contracts\EcomMicroService.Marketing.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\services\marketing\src\EcomMicroService.Marketing.EntityFrameworkCore\EcomMicroService.Marketing.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\..\services\cms\src\EcomMicroService.Cms.Application.Contracts\EcomMicroService.Cms.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\services\cms\src\EcomMicroService.Cms.EntityFrameworkCore\EcomMicroService.Cms.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\..\services\notification\src\EcomMicroService.Notification.Application.Contracts\EcomMicroService.Notification.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\services\notification\src\EcomMicroService.Notification.EntityFrameworkCore\EcomMicroService.Notification.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\..\services\projects\src\EcomMicroService.Projects.Application.Contracts\EcomMicroService.Projects.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\services\projects\src\EcomMicroService.Projects.EntityFrameworkCore\EcomMicroService.Projects.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\..\services\saas\src\EcomMicroService.SaaS.Application.Contracts\EcomMicroService.SaaS.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\services\saas\src\EcomMicroService.SaaS.EntityFrameworkCore\EcomMicroService.SaaS.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\EcomMicroService.Microservice.Shared\EcomMicroService.Microservice.Shared.csproj" />
        <ProjectReference Include="..\EcomMicroService.ServiceDefaults\EcomMicroService.ServiceDefaults.csproj" />
        <ProjectReference Include="..\EcomMicroService.Shared\EcomMicroService.Shared.csproj" />
    </ItemGroup>

</Project>
