<Project Sdk="Microsoft.NET.Sdk">

  

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>EcomMicroService.Notification</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Http" Version="$(MicrosoftAspNetVersion)" />
        <PackageReference Include="Volo.Abp.Mapperly" Version="$(AbpVersion)" />
        <PackageReference Include="Volo.Abp.Ddd.Application" Version="$(AbpVersion)" />
        <ProjectReference Include="..\EcomMicroService.Notification.Application.Contracts\EcomMicroService.Notification.Application.Contracts.csproj" />
        <ProjectReference Include="..\EcomMicroService.Notification.Domain\EcomMicroService.Notification.Domain.csproj" />
    </ItemGroup>

</Project>
