<Project Sdk="Microsoft.NET.Sdk">

  

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>EcomMicroService.SaaS</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Volo.Abp.Ddd.Domain" Version="$(AbpVersion)" />
        <PackageReference Include="Volo.Abp.TenantManagement.Domain" Version="$(AbpVersion)" />
        <ProjectReference Include="..\EcomMicroService.SaaS.Domain.Shared\EcomMicroService.SaaS.Domain.Shared.csproj" />
    </ItemGroup></Project>
